# Full herb compendium; inventory keys via herbs.herb_inventory_key
# habitat: "wild" (territory), "roadside", "compound"
# packs: pack-specific territories; "greyspire" (mountain), "mistmoor" (swamp),
#        "silverrush" (river), "thistlehide" (forest)

def _h(name, rarity, effect, packs=(), cures=(), poison=False, habitat=("wild",),
       side_effects="", preparation="", prep_methods=()):
    return {
        "name": name,
        "rarity": rarity,
        "packs": packs,
        "effect": effect,
        "cures": cures,
        "poison": poison,
        "habitat": habitat,
        "side_effects": side_effects,
        "preparation": preparation,
        "prep_methods": prep_methods,
    }


HERBS = {
    "adders_tongue": _h(
        "Adder's Tongue",
        "common",
        "reroll failed poison save with advantage if within 1 minute of sting; juice treats swollen eyes and cleans deep wounds.",
        cures=("mild_poison", "swollen_eye", "deep_gash", "shaking_sickness"),
        side_effects="can cause swelling, blistering, itching; toxic in large amounts; nausea, vomiting, diarrhea.",
        preparation="fresh roots or leaves simmered in milk; juice infused in apple cider.",
    ),
    "alder_bark": _h(
        "Alder Bark",
        "uncommon",
        "chewed and applied to wounds; prevents infection and reduces swelling; soothes toothache and gum pain; settles gut sickness. fresh bark causes vomiting; only use dried.",
        packs=("mistmoor",),
        cures=("tooth_infection", "infected_wound", "diarrhea"),
        side_effects="fresh bark causes severe vomiting; prolonged use may cause low potassium, heart problems.",
        preparation="bark chewed directly or applied as poultice; decoction used as mouthwash.",
    ),
    "arnica": _h(
        "Arnica",
        "rare",
        "halves bruise and sprain recovery (external only); anti-inflammatory poultice for joint pain. never eat; internal use is lethal.",
        packs=("greyspire",),
        cures=("sprained_leg", "punctured_paw", "arthritis"),
        side_effects="highly toxic if ingested; nausea, vomiting, irregular heartbeat, coma; topical may cause itching or rash.",
        preparation="external use only as gel, cream, or ointment; homeopathic dilutions are safer.",
    ),
    "beech_leaves": _h(
        "Beech Leaves",
        "common",
        "carry herbs; nut oil prevents infection and clears minor surface wounds. leaf tea is mildly antiseptic and eases leaf-bare cough.",
        cures=("leafbare_cough", "infected_wound"),
        side_effects="excessive intake may be toxic; unripe nuts cause vomiting, diarrhea, abdominal pain.",
        preparation="leaves used in teas; ointments for burns, sores, and ulcers.",
    ),
    "bindweed": _h(
        "Bindweed Vines",
        "common",
        "relieves gut complaints and urinary problems; immune-stimulating tonic for fever. tough vines lash splints to broken bones, speeding supported breaks (bone healing minus 7 days). strong laxative in large amounts; use sparingly.",
        cures=("eating_distress", "urinary_infection", "influenza", "constipation"),
        side_effects="strong laxative; large amounts cause stomach pain; toxic to livestock.",
        preparation="leaves may be cooked to reduce oxalic acid; seeds used as purgative.",
    ),
    "blackberry": _h(
        "Blackberry (Bramble)",
        "common",
        "soothes insect stings and ends non-magical venom; root bark is strongly astringent; settles diarrhea and gut upsets.",
        cures=("diarrhea", "eating_distress", "infected_wound", "mild_poison"),
        side_effects="prolonged or high-dose use may cause digestive upset or constipation from tannins.",
        preparation="leaves chewed into pulp and applied to stings; root bark used internally.",
    ),
    "bloodroot": _h(
        "Bloodroot",
        "restricted",
        "3d6 poison damage (dc 16 half). prolonged contact causes tissue damage and scarring.",
        poison=True,
        side_effects="nausea, vomiting, drowsiness, vertigo, contact dermatitis; topical use can cause tissue damage.",
        preparation="used in toothpaste and mouthwash; traditional salves; extreme caution.",
    ),
    "boneset": _h(
        "Boneset",
        "common",
        "reroll failed disease save with advantage; take the better result. slows early rabies (one sunrise, no cure). eases deep respiratory congestion and fever pain. fresh plant is toxic; always dried.",
        packs=("mistmoor",),
        cures=("influenza", "leafbare_cough"),
        side_effects="large amounts cause severe diarrhea; contains hepatotoxic pyrrolizidine alkaloids; liver damage.",
        preparation="traditional use at 2g of leaves and flowers.",
    ),
    "borage": _h(
        "Borage",
        "common",
        "extra milk for nursing mother; one additional pup. reduces fever, eases cough, and calms anxiety and low spirits. must be used fresh; drying destroys properties.",
        cures=("influenza", "leafbare_cough", "anxiety", "depression"),
        side_effects="upset stomach, headache, nausea; possible liver damage with prolonged use.",
        preparation="must be used fresh, never dried; leaves and roots chewed and eaten.",
    ),
    "broom": _h(
        "Broom",
        "common",
        "bind broken bones and splint fractures; anti-inflammatory poultice for bruising and sprains; move at half speed without worsening. toxic in large doses; cardiac effects and weakness.",
        cures=("fractured_rib", "sprained_leg", "broken_jaw"),
        side_effects="contains toxic alkaloids; weakness, blurred vision, cardiac arrhythmias, nausea.",
        preparation="1 tsp chopped flower shoots in water 3-4 times daily; traditional.",
    ),
    "burdock_root": _h(
        "Burdock Root",
        "common",
        "poultice draws infection from bites and open wounds after 24h rest. eases skin disease and early growth-sickness. diuretic; avoid when dehydrated.",
        cures=("infected_wound", "deep_gash", "mange", "cancer"),
        side_effects="generally safe; may cause allergic reactions; high doses may cause liver injury.",
        preparation="root dug up, washed, chewed into pulp, applied to bites and wounds.",
    ),
    "burnet": _h(
        "Burnet",
        "common",
        "leaf applied to cuts staunches bleeding; settles gut sickness and deep wounds. 1 leaf per day ignores first exhaustion from a forced march.",
        cures=("sprained_leg", "diarrhea", "deep_gash"),
        side_effects="limited documented side effects.",
        preparation="applied as poultice; root used as astringent and tonic.",
    ),
    "catchweed": _h(
        "Catchweed Burrs",
        "common",
        "burrs hold poultices in place; extends duration 4 hours without harming the pelt. clears urinary complaints.",
        cures=("urinary_infection",),
        side_effects="limited documented side effects.",
        preparation="burrs attached to pelt over poultices.",
    ),
    "cattail": _h(
        "Cattail",
        "common",
        "pollen is hemostatic; stops bleeding like yarrow; analgesic; mildly antiseptic.",
        packs=("silverrush", "mistmoor"),
        cures=("deep_gash", "sprained_leg", "infected_wound"),
        side_effects="generally safe short-term; may cause mild gi discomfort; avoid in pregnancy.",
        preparation="pollen taken as capsules; young shoots and rhizomes eaten.",
    ),
    "celandine": _h(
        "Celandine",
        "common",
        "removes eye swelling and restores eyesight within 1 hour; treats liver complaints and gallstones; eases leaf-bare cough. large doses cause vomiting; use sparingly.",
        cures=("swollen_eye", "hepatitis", "leafbare_cough", "gallstones"),
        side_effects="large quantities cause vomiting and purging; fresh juice is local irritant; may cause dry mouth.",
        preparation="juice trickled into the eye.",
    ),
    "chamomile": _h(
        "Chamomile",
        "common",
        "advantage on wisdom saves vs fear for 1 hour. reduces fever, calms nerves, soothes eating troubles, and eases grief. mildly sedative; aids sleep and recovery.",
        habitat=("compound",),
        cures=("anxiety", "insomnia", "eating_distress", "influenza", "grief_melancholy", "delirium"),
        side_effects="generally safe; allergic reactions possible, especially in ragweed-sensitive wolves.",
        preparation="leaves and flowers consumed; tea made from flowers.",
    ),
    "chervil": _h(
        "Chervil",
        "common",
        "removes nausea; eases redscratch itch; leaf juice clears infected wounds. stimulates appetite and eases gut troubles in wasting wolves.",
        cures=("infected_wound", "diarrhea", "redscratch", "eating_distress", "wasting_sickness"),
        side_effects="generally safe; potential for mild gi discomfort or allergic reactions.",
        preparation="juice extracted from leaves or root for infected wounds and bellyache.",
    ),
    "chickweed": _h(
        "Chickweed",
        "common",
        "ends green-cough (3 doses per 24 hours); poultice soothes skin conditions and reduces mild swelling. anti-bacterial; promotes wound healing.",
        habitat=("roadside", "compound"),
        cures=("cough", "leafbare_cough", "infected_wound"),
        side_effects="high doses may cause vertigo, weakness, headache, difficulty breathing.",
        preparation="used as tea or topical application.",
    ),
    "cobnuts": _h(
        "Cobnuts",
        "common",
        "+1 stealth when approaching prey; rich in protein and fiber; restores +8 hunger on patrol.",
        cures=(),
        side_effects="may trigger allergic reactions in tree-nut-sensitive individuals.",
        preparation="eaten raw or cooked.",
    ),
    "cobwebs": _h(
        "Cobwebs",
        "common",
        "auto-stabilize dying wolf; bandages deep gashes and burns. required for `/medic action:field_dressing`. can increase infection risk if wound is already dirty; clean wound first.",
        cures=("dying", "deep_gash", "shaking_sickness", "scorched_hide"),
        side_effects="can cause increased risk of infection if wound is dirty.",
        preparation="gathered in a swath and applied to bleeding wound; wrapped around injury.",
        prep_methods=("poultice",),
    ),
    "coltsfoot": _h(
        "Coltsfoot",
        "common",
        "ends green-cough after 1 dose; leaf pulp soothes cracked and sore paw pads. toxic long-term; contains alkaloids that damage the liver; use short-term only.",
        cures=("cough", "leafbare_cough", "punctured_paw", "asthma"),
        side_effects="likely unsafe; contains hepatotoxic pyrrolizidine alkaloids that damage liver and lungs.",
        preparation="leaves chewed to pulp and eaten for shortness of breath.",
    ),
    "comfrey": _h(
        "Comfrey",
        "uncommon",
        "poultice heals 1d4 hp on deep wounds; stimulates tissue regeneration and prevents scar tissue. do not eat; pyrrolizidine alkaloids cause fatal liver damage.",
        packs=("thistlehide",),
        cures=("fractured_rib", "broken_jaw", "sprained_leg", "deep_gash"),
        side_effects="do not take internally; contains pyrrolizidine alkaloids causing fatal liver damage; may cause abortion.",
        preparation="roots chewed into poultice and applied externally.",
    ),
    "coneflower": _h(
        "Coneflower (Echinacea)",
        "common",
        "advantage on infection saves within 1h of injury; boosts immune system. shortens cough and fever duration. allergic reactions possible; watch for hives.",
        packs=("greyspire",),
        cures=("infected_wound", "influenza", "leafbare_cough"),
        side_effects="common: nausea, upset stomach; allergic reactions possible including anaphylaxis.",
        preparation="tea, tincture, tablet, or capsule.",
    ),
    "daisy": _h(
        "Daisy",
        "common",
        "ignore arthritis and joint pain penalties for 8 hours; leaf promotes wound healing and skin repair. tea eases sleeplessness and mild low spirits.",
        cures=("deep_gash", "leafbare_cough", "infected_wound", "insomnia", "sprained_leg", "arthritis"),
        side_effects="mildly toxic to humans and pets.",
        preparation="various preparations; tea, topical applications.",
    ),
    "dandelion": _h(
        "Dandelion",
        "common",
        "soothes stings and flushes fever; supports liver health; eases eating distress and leptospirosis. diuretic.",
        habitat=("roadside", "compound"),
        cures=("eating_distress", "hepatitis", "influenza", "leptospirosis", "mild_poison"),
        side_effects="generally safe; rare upset stomach or diarrhea; allergic reactions possible.",
        preparation="leaves and stems eaten; root made into tea.",
    ),
    "deadly_nightshade": _h(
        "Deadly Nightshade",
        "restricted",
        "confusion then paralysis (wis dc 15). as few as 5 berries kill an adult. touch may be toxic.",
        poison=True,
        side_effects="extremely toxic; all parts poisonous; symptoms: blurred vision, seizures, death.",
        preparation="no safe preparation for lay use.",
    ),
    "deathberries": _h(
        "Deathberries (Yew)",
        "restricted",
        "mercy killing; medic knowledge only. seeds kill within minutes; yarrow used as antidote to induce vomiting.",
        poison=True,
        side_effects="seeds can kill within minutes; poisonous to most animals.",
        preparation="seeds consumed for euthanasia; yarrow used as antidote to induce vomiting.",
    ),
    "dried_skullcap": _h(
        "Dried Skullcap",
        "uncommon",
        "sedative rest for concussion recovery; anti-anxiety and anti-inflammatory. treats nervous conditions, seizure-like episodes, depression, grief. high doses cause confusion and irregular heartbeat.",
        cures=("concussion", "dementia", "feral_shift", "anxiety", "delirium", "obsession", "pack_madness", "insomnia", "grief_melancholy"),
        side_effects="generally well-tolerated; may cause confusion, stupor, vivid dreams, mild digestive disturbances.",
        preparation="1-2g dried herb steeped in 1 cup water for 5 minutes.",
    ),
    "dock": _h(
        "Dock",
        "common",
        "restores cracked paw pads after 1 day rest; leaf chewed and applied soothes scratches and infected wounds. root decoction treats liver complaints, gut sickness, and leaf-bare cough.",
        cures=("leafbare_cough", "hepatitis", "diarrhea", "punctured_paw", "infected_wound"),
        side_effects="oxalate content may cause gi symptoms or kidney damage; avoid mature or uncooked leaves.",
        preparation="leaf chewed and applied to scratches.",
    ),
    "douglas_sagewort": _h(
        "Douglas' Sagewort",
        "common",
        "prevents infection 24h; soothes poison-ivy rash and insect stings; neutralizes mild poison. internal use may have mutagenic effects; use topically.",
        packs=("greyspire",),
        cures=("poison_ivy", "infected_wound", "mild_poison"),
        side_effects="contains thujone with mild psychoactive properties; internal use may have mutagenic effects.",
        preparation="leaves and stems dried, burned as incense or drunk as tea.",
    ),
    "edelweiss": _h(
        "Edelweiss",
        "very_rare",
        "ends bellyache and eating troubles; suppresses leaf-bare cough for 4 hours.",
        packs=("greyspire",),
        cures=("diarrhea", "eating_distress", "leafbare_cough"),
        side_effects="generally safe; coumarins may damage liver and kidneys in large amounts.",
        preparation="various traditional preparations.",
    ),
    "elder": _h(
        "Elder (external)",
        "common",
        "treats sprains; toxic if eaten (dc 14 or 2d4 poison). bark and leaf poultice reduce swelling. unripe berries and all internal parts cause severe vomiting.",
        cures=("sprained_leg",),
        poison=True,
        side_effects="poisoning: vomiting, diarrhea, weakness, coma; unripe berries and other parts toxic.",
        preparation="requires careful preparation; unripe or uncooked parts are toxic.",
    ),
    "elderberry": _h(
        "Elderberry",
        "rare",
        "advantage on disease saves for 3 sunrises; rich in antioxidants. reduces weeping-scale, flu, and leaf-bare cough. raw or unripe berries cause violent vomiting; must be fully ripe.",
        packs=("mistmoor",),
        cures=("hard_paw", "influenza", "leafbare_cough"),
        side_effects="raw or unripe berries, leaves, stems are toxic; can cause nausea, vomiting, severe diarrhea; cooked berries are safe.",
        preparation="must be cooked; raw or unripe berries are toxic.",
    ),
    "fennel": _h(
        "Fennel",
        "common",
        "extra day without food before exhaustion sets in; eases chest tightness and leaf-bare cough; settles digestive cramps, eating troubles, and bloat. antifungal and antibacterial.",
        habitat=("compound",),
        cures=("eating_distress", "leafbare_cough", "bloat", "infected_wound"),
        side_effects="generally safe; rare: stomach upset, seizures; oil may cause hallucinations.",
        preparation="seeds used as spice or tea; oil used with caution.",
    ),
    "feverfew": _h(
        "Feverfew",
        "common",
        "reduces inflammation and fever; advantage on disease saves for 1 day. treats swollen eyes and head pain. chewing fresh leaves causes mouth sores; use dried only.",
        cures=("influenza", "redscratch", "pox", "rot_lung", "milk_fever", "swollen_eye", "leafbare_cough"),
        side_effects="5-15% develop mouth ulcers or gi irritation; may increase bleeding; abrupt stop may cause rebound headaches.",
        preparation="dried leaf or extract taken orally.",
    ),
    "foxglove": _h(
        "Foxglove",
        "restricted",
        "deadly heart poison (dc 18 or die in 1d4 min). narrow margin between medicine and death. all parts poisonous.",
        poison=True,
        side_effects="extremely toxic; all parts poisonous; narrow therapeutic index; toxicity: vomiting, cardiac arrhythmias, death.",
        preparation="no safe preparation for lay use; professional medical use only.",
    ),
    "goldenrod": _h(
        "Goldenrod",
        "rare",
        "+2 hp per 8h rest. slows early rabies (+2 next save, no cure). anti-inflammatory and diuretic; clears urinary infection and wound infection.",
        cures=("infected_wound", "deep_gash", "urinary_infection", "lyme"),
        side_effects="generally well-tolerated; may cause heartburn; allergic reactions possible.",
        preparation="tea, tincture, or supplement.",
    ),
    "heather": _h(
        "Heather",
        "common",
        "sweetens bitter herb mixtures. tea is anti-inflammatory and antiseptic; eases gut upsets, mild cough, and nervy tension.",
        cures=("diarrhea", "leafbare_cough", "anxiety"),
        side_effects="possibly safe; no side effects reported; safety in pregnancy not established.",
        preparation="tender tops and flowers made into decoction; roots in milk for diarrhea.",
    ),
    "holly_berries": _h(
        "Holly Berries",
        "restricted",
        "2d4 poison (dc 12 half). leaves cause diarrhea and vomiting; leaf spines can puncture the digestive tract.",
        poison=True,
        side_effects="berries poisonous; leaves cause diarrhea, nausea, vomiting; leaf spines may tear mouth.",
        preparation="avoid ingestion; external use only with caution.",
    ),
    "honey": _h(
        "Honey",
        "common",
        "feeds starving pups (+10 hunger, -1 exhaustion); sweetens `/pupcare action:feed`. adults: -1 starvation exhaustion when depleted. soothes smoke-damaged throat and cough; antibacterial wound dressing.",
        cures=("leafbare_cough", "deep_gash"),
        side_effects="generally safe; may cause blood sugar spikes; allergic reactions possible.",
        preparation="used directly or mixed with other herbs.",
    ),
    "horsetail": _h(
        "Horsetail",
        "common",
        "+3 medicine to stabilize dying; hemostatic poultice closes wounds and stops bleeding. antimicrobial; treats torn claws, paw wounds, and urinary complaints. long-term use may cause thiamine deficiency.",
        cures=("deep_gash", "torn_claw", "punctured_paw", "urinary_infection"),
        side_effects="contains thiaminase; long-term use may cause thiamine deficiency; high doses may cause liver injury.",
        preparation="tea, poultice, or supplement.",
    ),
    "ivy_vines": _h(
        "Ivy Vines",
        "common",
        "preserves dried herbs 2 extra weeks; leaf extract thins chest mucus and opens airways; eases fever, leaf-bare cough, and asthma.",
        cures=("leafbare_cough", "influenza", "asthma"),
        side_effects="rarely causes noticeable side effects; nausea and vomiting possible with excessive doses.",
        preparation="pill, powder, or extract.",
    ),
    "jewelweed": _h(
        "Jewelweed",
        "common",
        "sap neutralizes poison-ivy rash; cools bee and nettle stings. anti-fungal; soothes liver complaints and eases gut sickness.",
        habitat=("roadside", "wild"),
        cures=("poison_ivy", "mild_poison", "hepatitis", "diarrhea"),
        side_effects="possibly safe; may cause digestive upset if consumed in high amounts.",
        preparation="sap applied directly to skin; tea traditionally used.",
    ),
    "juniper_berry": _h(
        "Juniper Berries",
        "common",
        "neutralizes mild poison; antiseptic berries slow infection in wounds; clears urinary complaints and diarrhea. excessive use damages kidneys over time.",
        cures=("mild_poison", "diarrhea", "urinary_infection", "infected_wound"),
        side_effects="allergic reactions possible; excessive use may cause kidney damage; large doses cause convulsions.",
        preparation="berries eaten directly; leaves used for respiratory issues.",
    ),
    "knotgrass": _h(
        "Knotgrass",
        "common",
        "cures diarrhea; kills internal parasites and worms in 1 day; drives off fleas. eases urinary complaints and leaf-bare cough. no serious side effects reported.",
        habitat=("roadside", "compound"),
        cures=("diarrhea", "fleas", "leafbare_cough", "urinary_infection", "worms"),
        side_effects="no serious side effects reported; may cause mild gi discomfort.",
        preparation="1.5g taken 3-5 times daily; infusions for kidney and bladder conditions.",
        prep_methods=("chewed", "infusion"),
    ),
    "labrador_tea": _h(
        "Labrador Tea",
        "common",
        "ends wheezing for 4 hours; settles gut sickness; source of vitamin c. toxic in large amounts; causes vomiting, diarrhea, paralysis, and death. maximum one dose per day.",
        cures=("leafbare_cough", "diarrhea", "asthma"),
        side_effects="contains ledol and grayanotoxin; toxic; large amounts cause vomiting, gastroenteritis, diarrhea, delirium, spasms, death.",
        preparation="dried leaves brewed as tea; maximum one cup per day.",
    ),
    "lambs_ear": _h(
        "Lamb's Ear",
        "common",
        "fuzzy leaves pressed on wounds stop bleeding and soothe insect stings. advantage on disease saves until next sunrise. antiseptic; no known toxicity.",
        habitat=("roadside",),
        cures=("infected_wound", "mild_poison"),
        side_effects="not known to be toxic; possible allergic reactions.",
        preparation="fuzzy leaves applied directly to skin as compress.",
    ),
    "lavender": _h(
        "Lavender",
        "common",
        "cures fever and chills; hides death-scent at burial. calming; advantage vs fear when inhaled; eases grief and nightmares. large oral doses cause nausea.",
        habitat=("compound",),
        cures=("influenza", "anxiety", "insomnia", "grief_melancholy", "night_terrors"),
        side_effects="generally well-tolerated; allergic skin reactions possible; large oral doses may cause nausea.",
        preparation="leaves or flowers eaten; aromatherapy; essential oil; diluted.",
    ),
    "mullein": _h(
        "Mullein",
        "rare",
        "heals yellowcough and rot-lung lung damage; medics use it for full recovery. expectorant and antiviral; shortens cough duration. fda-classified as generally safe.",
        packs=("greyspire", "mistmoor"),
        habitat=("roadside",),
        cures=("yellowcough", "rot_lung", "cancer", "asthma", "bronchitis"),
        side_effects="no common or severe side effects; tiny hairs may cause skin irritation; seeds contain rotenone.",
        preparation="tea, tincture, or smoked.",
    ),
    "lungwort": _h(
        "Lungwort",
        "rare",
        "also heals yellowcough and rot-lung when mullein is scarce. soothes respiratory irritation; expectorant and wound healing. use in moderation; may contain liver-affecting substances.",
        packs=("greyspire", "mistmoor"),
        cures=("yellowcough", "rot_lung", "cancer", "asthma", "bronchitis"),
        side_effects="generally safe in moderation; large doses may cause stomach discomfort; may contain liver-toxic substances.",
        preparation="tea, tincture, topical application.",
    ),
    "marsh_mallow": _h(
        "Marsh-Mallow Root",
        "uncommon",
        "soothes rot-lung fever and wheeze; mucilaginous root coats sore throat and eases leaf-bare cough. demulcent for bruises, swellings, and sprains. may lower blood sugar.",
        packs=("mistmoor",),
        cures=("rot_lung", "leafbare_cough", "sprained_leg", "asthma"),
        side_effects="generally recognized as safe; rare: bloating, gas, fullness; may lower blood sugar.",
        preparation="tea, topical application, bath additive.",
    ),
    "belly_rip_fungus": _h(
        "Belly-Rip Fungus",
        "rare",
        "glow-fungus from the belly-rip sinkhole; only cure for rot-lung necrosis.",
        packs=("mistmoor",),
        cures=("rot_lung",),
        side_effects="unknown; use with extreme caution.",
        preparation="applied directly to necrotic tissue; healer's discretion.",
    ),
    "death_cap": _h(
        "Death-Cap Mushroom",
        "rare",
        "pale mushroom found only in the rotting mere. intensely toxic; 3d6 poison (dc 18 half). causes organ failure and seizures. healers may use trace amounts experimentally.",
        packs=("mistmoor",),
        poison=True,
        habitat=("rotting_mere",),
        side_effects="extremely toxic; one of the most lethal mushrooms; causes organ failure, seizures, nausea; fatal if ingested.",
        preparation="no safe preparation; experimental use only by experienced healers.",
    ),
    "lizards_tail": _h(
        "Lizard's Tail",
        "common",
        "removes 1 fever exhaustion; anti-inflammatory and diuretic. sedative rhizome eases fever, body aches, and urinary complaints. contains saponins; causes nausea if too much is eaten.",
        packs=("mistmoor",),
        cures=("influenza", "urinary_infection"),
        side_effects="contains saponins; poisonous when ingested; causes irritation, nausea, vomiting.",
        preparation="dried roots ground into powder; tea or infusion.",
    ),
    "meadowsweet": _h(
        "Meadowsweet",
        "uncommon",
        "ignore 1 pain exhaustion for 4 hours; pain relief for 1 sunrise; ignores chronic pain and arthritis penalties. contains salicylates; eases gut upset, diarrhea, and fever. increases bleeding risk if used with wounds.",
        packs=("silverrush",),
        cures=("sprained_leg", "diarrhea", "eating_distress", "influenza", "lyme", "arthritis"),
        side_effects="contains salicylates; increases bleeding risk; large amounts or long-term use possibly unsafe.",
        preparation="tea, tincture; traditional adult dose: 2.5-3.5g flower or 4-5g herb daily.",
    ),
    "mountain_ash": _h(
        "Mountain Ash (Rowan)",
        "common",
        "bitter bark eases fever and weeping-scale, soothes liver complaints; choleretic. berries require caution; large amounts cause stomach damage.",
        cures=("influenza", "hard_paw", "hepatitis"),
        side_effects="fresh berries possibly unsafe; large amounts cause stomach irritation, vomiting, kidney damage.",
        preparation="bark for medicinal use; berries require caution.",
    ),
    "oak_bark": _h(
        "Oak Bark",
        "common",
        "stops bleeding; +2 stabilize. astringent and antiviral; treats acute diarrhea, reduces inflammation, and prevents infection in cuts and scrapes. prolonged use damages liver.",
        packs=("thistlehide",),
        cures=("deep_gash", "infected_wound", "diarrhea"),
        side_effects="oral use may cause stomach upset; topical may irritate skin; prolonged use may cause kidney or liver damage.",
        preparation="tea for diarrhea; topical applications.",
    ),
    "oleander": _h(
        "Oleander",
        "restricted",
        "4d6 poison, no antidote (dc 18 half). one of the most poisonous plants known; all parts lethal. sap causes severe eye inflammation.",
        poison=True,
        side_effects="one of the most poisonous plants; all parts toxic; small amounts lethal.",
        preparation="no safe preparation for lay use.",
    ),
    "parsley": _h(
        "Parsley",
        "common",
        "ends lactation within 6 hours; eases milk-fever and eating troubles. analgesic, antibacterial, and digestive aid. parsley oil is hepatotoxic in high doses; use leaves only.",
        habitat=("compound",),
        cures=("milk_fever", "wasting_sickness", "eating_distress", "urinary_infection"),
        side_effects="parsley oil: headache, convulsions, kidney damage; psoralens cause photodermatitis; avoid in pregnancy.",
        preparation="used as food or tea; oil requires caution.",
    ),
    "passionflower": _h(
        "Passionflower",
        "uncommon",
        "eases racing thoughts and insomnia; reduces anxiety and feral drift.",
        habitat=("compound",),
        cures=("anxiety", "insomnia", "feral_shift"),
        side_effects="common: dizziness, drowsiness, confusion; not for use by pregnant wolves.",
        preparation="tea or dietary supplement.",
    ),
    "pine_needle": _h(
        "Pine Needles",
        "common",
        "tea ends coughing after 1 dose; expectorant for chest congestion. supports urinary tract and immune system. avoid in pregnancy; may cause uterine contractions.",
        packs=("greyspire",),
        cures=("cough", "leafbare_cough", "urinary_infection", "asthma"),
        side_effects="may cause uterine contractions; avoid pregnancy; large quantities may cause stomach upset.",
        preparation="tea; essential oil; diluted, with caution.",
    ),
    "pine_bark": _h(
        "Pine Bark",
        "common",
        "inner bark eases leaf-bare cough and frost-nipped paws; reduces inflammation and eases breathing and asthma.",
        packs=("greyspire",),
        cures=("leafbare_cough", "punctured_paw", "asthma"),
        side_effects="minor: stomach upset, headaches, dizziness; may increase bleeding risk.",
        preparation="extract supplement.",
    ),
    "plantain": _h(
        "Plantain",
        "uncommon",
        "gentle wound remedy; cleanses torn claws and deep gashes. expectorant; opens airways and eases chest illness. astringent and hemostatic. anaphylaxis possible in rare cases.",
        packs=("thistlehide",),
        habitat=("roadside", "compound"),
        cures=("leafbare_cough", "deep_gash", "punctured_paw", "torn_claw", "asthma", "bronchitis"),
        side_effects="anaphylaxis possible; mild: nausea, vomiting, bloating; high doses may cause serious allergic reactions.",
        preparation="tea, tincture, poultice.",
    ),
    "poison_ivy": _h(
        "Poison Ivy",
        "restricted",
        "contact: -1d4 cha, disadvantage stealth 3 days. contains urushiol; causes severe skin rash and mouth or throat irritation if eaten.",
        poison=True,
        side_effects="highly toxic; contains urushiol; causes severe skin irritation; ingestion causes severe mouth and throat irritation.",
        preparation="avoid; no safe preparation for medicinal use.",
    ),
    "poppy_seeds": _h(
        "Poppy Seeds",
        "common",
        "sedative and pain relief; unconscious rest 1 sunrise. calms shock and emotional distress. mild hypnotic; aids sleep and reduces anxiety. excessive intake is toxic.",
        habitat=("compound",),
        cures=("insomnia", "anxiety", "shock_emotional", "grief_melancholy"),
        side_effects="generally safe; excessive intake may cause digestive discomfort; may cause positive drug test.",
        preparation="seeds consumed; flower heads for coughs; petals and leaves chewed for sleep.",
    ),
    "prickly_ash": _h(
        "Prickly Ash",
        "rare",
        "ends frozen-paw numbness; numbs tooth pain for 1 hour. improves circulation to cold extremities; analgesic and anti-inflammatory. may increase bleeding risk.",
        packs=("greyspire",),
        cures=("tooth_infection", "punctured_paw", "arthritis"),
        side_effects="no known major side effects; may cause allergic reactions; may increase bleeding risk.",
        preparation="bark and berries used medicinally.",
    ),
    "purple_loosestrife": _h(
        "Purple Loosestrife",
        "common",
        "staunches bleeding on stitched wounds; reduces bleed timer; cures diarrhea. antibiotic and astringent; treats bacterial infections. sedative in large amounts.",
        packs=("silverrush",),
        habitat=("roadside",),
        cures=("deep_gash", "diarrhea", "infected_wound"),
        side_effects="astringent properties may cause gi distress in large quantities.",
        preparation="tea; flowering tops dried.",
    ),
    "ragweed": _h(
        "Ragweed",
        "common",
        "3 leaves removes 1 exhaustion. astringent properties ease mild respiratory inflammation and liver complaints. highly allergenic; avoid in wolves with known pollen sensitivity.",
        habitat=("roadside",),
        cures=("leafbare_cough", "hepatitis", "allergy"),
        side_effects="highly allergenic; causes hay fever, contact dermatitis, respiratory distress.",
        preparation="tea; caution, highly allergenic.",
    ),
    "ragwort": _h(
        "Ragwort",
        "common",
        "elder hunts at full speed for 1 day. eases joint and limb stiffness. toxic; contains pyrrolizidine alkaloids; causes liver damage with repeated use. lethal to grazing animals.",
        cures=("sprained_leg",),
        side_effects="toxic; contains pyrrolizidine alkaloids causing liver toxicity; fatal to grazing animals.",
        preparation="avoid; no safe preparation.",
    ),
    "raspberry_leaves": _h(
        "Raspberry Leaves",
        "common",
        "advantage on birth hemorrhage saves; rich in vitamins and minerals. strongly astringent; eases mild diarrhea and chest cough. detoxifying tonic.",
        cures=("diarrhea", "leafbare_cough"),
        side_effects="generally safe; may cause diarrhea, hypoglycemia, acute liver injury; may cause premature labor.",
        preparation="tea.",
    ),
    "rosemary": _h(
        "Rosemary",
        "common",
        "hides death-scent at burial. relieves grief, decreases stress, calms anxiety; anti-inflammatory and digestive aid. large doses cause vomiting and kidney damage; use sparingly.",
        habitat=("compound",),
        cures=("grief_melancholy", "dementia", "chronic_stress", "anxiety", "obsession"),
        side_effects="large amounts cause vomiting, sun sensitivity, kidney damage; undiluted oil toxic.",
        preparation="culinary herb, tea, essential oil; diluted.",
    ),
    "rush_stalks": _h(
        "Rush Stalks",
        "common",
        "hard stalks bind broken bones; lash splints with sticks (+2 medicine to set fractures). antispasmodic and expectorant. long-term use may cause thiamine deficiency.",
        packs=("mistmoor", "silverrush"),
        cures=("fractured_rib", "broken_jaw", "sprained_leg"),
        side_effects="contains thiaminase; long-term use may cause thiamine deficiency.",
        preparation="stalks boiled for diuretic; used as splint material.",
    ),
    "saffron": _h(
        "Saffron",
        "common",
        "auto-stabilize postpartum hemorrhage; ends milk-fever. sedative and expectorant; eases cough, anxiety, and grief. large doses (>5g) cause vomiting and bloody urine.",
        habitat=("compound",),
        cures=("dying", "milk_fever", "leafbare_cough", "anxiety", "grief_melancholy"),
        side_effects="generally safe up to 100mg daily; large doses (>5g) cause vomiting, dizziness, bloody urine; may cause miscarriage.",
        preparation="used as spice or supplement.",
    ),
    "sage": _h(
        "Sage",
        "common",
        "soothes sore throat; elders eat hard food longer. eases leaf-bare cough, eating troubles, and diarrhea. antimicrobial wash for infected wounds. extended use or large amounts cause seizures.",
        habitat=("compound",),
        cures=("leafbare_cough", "eating_distress", "diarrhea", "infected_wound"),
        side_effects="extended use or large amounts: restlessness, vomiting, vertigo, rapid heart rate, seizures, kidney damage.",
        preparation="tea, gargle, culinary herb.",
    ),
    "skunk_cabbage": _h(
        "Skunk Cabbage (dried)",
        "common",
        "treats severe cough and blackcough; antispasmodic for the chest. toxic fresh (dc 12); contains oxalates; causes mouth pain. overconsumption causes kidney failure.",
        cures=("cough", "leafbare_cough", "asthma"),
        side_effects="possibly safe in small amounts; large amounts cause nausea, vomiting, dizziness; contains oxalates.",
        preparation="ointment from roots boiled in oil; dried form only.",
    ),
    "slippery_elm": _h(
        "Slippery Elm",
        "uncommon",
        "eat or drink without pain for 8 hours. powdered bark soothes gut lining; treats diarrhea, eating troubles, and urinary inflammation. eases stress and anxiety. whole bark may cause miscarriage.",
        packs=("thistlehide",),
        cures=("broken_jaw", "diarrhea", "eating_distress", "anxiety", "urinary_infection"),
        side_effects="no known side effects orally; topical may cause contact dermatitis; whole bark may be abortifacient.",
        preparation="powdered bark; tea, tincture.",
    ),
    "snakeroot": _h(
        "Snakeroot",
        "common",
        "advantage vs snake venom saves; calms anxiety and promotes sleep. excessive use causes depression, nightmares, and severe diarrhea.",
        cures=("anxiety", "insomnia", "mild_poison"),
        side_effects="nasal congestion, sedation, gi upset, bradycardia; diarrhea, depression.",
        preparation="powdered root: 50-300mg daily.",
    ),
    "sorrel": _h(
        "Sorrel",
        "common",
        "stops heavy bleeding from deep wounds; restores appetite; analgesic for sprains; diuretic; clears urinary complaints. eases chest congestion. large amounts cause kidney damage; toxic in excess.",
        cures=("deep_gash", "leafbare_cough", "sprained_leg", "urinary_infection", "eating_distress"),
        side_effects="large amounts possibly unsafe; may increase kidney stone risk; contains oxalic acid.",
        preparation="leaves used fresh or cooked.",
    ),
    "stick": _h(
        "Straight Stick",
        "common",
        "thin twig for wolves in pain to bite during deep treatment; also used to lash splints.",
        habitat=("wild",),
        cures=(),
        side_effects="none; splinters possible if not smoothed.",
        preparation="gathered from any woody area.",
    ),
    "sticklewort": _h(
        "Sticklewort",
        "common",
        "neutralizes snake venom; astringent; treats diarrhea, leaf-bare cough, and infected wounds. hepatoprotective.",
        cures=("diarrhea", "leafbare_cough", "infected_wound", "mild_poison", "hepatitis"),
        side_effects="allergic reactions possible; caution for blood clotting issues.",
        preparation="tea, gargle, topical application.",
    ),
    "stinging_nettle": _h(
        "Stinging Nettle",
        "common",
        "with comfrey +1 broken bone healing day. dried leaves drive off fleas. reduces joint inflammation and clears urinary complaints. cook or dry before use; raw stings.",
        cures=("fractured_rib", "sprained_leg", "fleas", "urinary_infection", "lyme", "arthritis"),
        side_effects="generally safe in moderate amounts; common: constipation, diarrhea, upset stomach; touching plant causes irritation.",
        preparation="dried or cooked form safe; tea, tincture, supplement.",
    ),
    "swamp_milkweed": _h(
        "Swamp Milkweed",
        "very_rare",
        "breaks curses; only herb known to cure pox in its late stage. toxic; contains cardiac glycosides; causes dangerous heart issues in large doses.",
        packs=("mistmoor",),
        cures=("pox",),
        side_effects="toxic; contains cardiac glycosides; causes dangerous heart issues; lethal in large doses.",
        preparation="avoid; no safe preparation for lay use.",
    ),
    "sweet_sedge": _h(
        "Sweet Sedge",
        "common",
        "ends mild gut infection in 1 day; steadies belly-rip tremors; eases eating distress. digestive aid. likely unsafe internally; contains cancer-causing beta-isoasarone; use externally or in tiny amounts only.",
        cures=("diarrhea", "shaking_sickness", "eating_distress", "bloat"),
        side_effects="likely unsafe; contains cancer-causing beta-isoasarone; causes kidney damage, shaking, seizures.",
        preparation="avoid; no safe preparation.",
    ),
    "tansy": _h(
        "Tansy",
        "common",
        "halves sprain recovery time; expels internal parasites and worms; leaf suppresses leaf-bare cough. drives off fleas. toxic; contains thujone; lethal in pregnancy; causes miscarriage.",
        cures=("sprained_leg", "fleas", "leafbare_cough", "worms"),
        side_effects="toxic; contains thujone; causes vomiting, severe diarrhea, tremors, kidney and liver damage, seizures; not for pregnant wolves.",
        preparation="leaves, flowers, stems eaten together; extreme caution.",
    ),
    "thyme": _h(
        "Thyme",
        "common",
        "ends minor pain for 2 hours. mucolytic expectorant for chest congestion. calms anxiety and aids restful sleep. antifungal and antibacterial.",
        habitat=("compound",),
        cures=("anxiety", "insomnia", "leafbare_cough", "asthma"),
        side_effects="possibly safe short-term; allergic reactions, dizziness, stomach upset; rare hypersensitivity.",
        preparation="consumed; tea, culinary herb.",
    ),
    "tormentil": _h(
        "Tormentil",
        "common",
        "+2 medicine for any injury. more tannin than oak bark; strongly astringent; treats diarrhea and acute gut sickness; soothes throat inflammation and infected wounds.",
        cures=("diarrhea", "leafbare_cough", "infected_wound"),
        side_effects="generally well-tolerated; mild stomach pain or heartburn possible.",
        preparation="tea, tincture, topical.",
    ),
    "valerian": _h(
        "Valerian",
        "common",
        "calms shock; unconscious 1d4 hours. reduces anxiety, eating troubles, feral drift, and grief. aids insomnia. withdrawal symptoms after long-term use; wean slowly.",
        habitat=("compound",),
        cures=("anxiety", "insomnia", "feral_shift", "eating_distress", "grief_melancholy", "shock_emotional"),
        side_effects="generally well-tolerated; common: dizziness, headache, daytime drowsiness; withdrawal symptoms if discontinued.",
        preparation="tea, tincture, supplement.",
    ),
    "watermint": _h(
        "Watermint",
        "common",
        "removes nausea in 10 minutes. analgesic, antiseptic, and antispasmodic; treats cough, wounds, gut sickness, and liver complaints. not for pregnant wolves; may cause premature birth.",
        cures=("leafbare_cough", "infected_wound", "diarrhea", "eating_distress", "hepatitis", "bloat", "leptospirosis"),
        side_effects="not for pregnant mothers; may cause premature birth or miscarriage; toxic to sheep.",
        preparation="chewed into pulp; tea from fresh or dried leaves.",
    ),
    "water_hemlock": _h(
        "Water Hemlock",
        "restricted",
        "lethal poison (dc 20 half, still 6d6). one of the most poisonous plants; cicutoxin causes death within 15 minutes. all parts are poisonous; even small amounts cause convulsions.",
        poison=True,
        side_effects="one of the most poisonous plants; contains cicutoxin; even small amounts cause muscle spasms, respiratory failure, death within an hour.",
        preparation="extremely dangerous; no safe preparation.",
    ),
    "wild_cherry_bark": _h(
        "Wild Cherry Bark",
        "common",
        "stops coughing for 2 hours, even blackcough; sedative and digestive tonic. calms anxiety. contains cyanogenic glycosides; short-term use only (10-14 days); large doses toxic.",
        cures=("cough", "leafbare_cough", "diarrhea", "anxiety"),
        side_effects="generally safe in small amounts; excessive doses toxic due to cyanogenic glycosides; short-term use only.",
        preparation="bark tea or syrup; short-term use only.",
    ),
    "wild_garlic": _h(
        "Wild Garlic",
        "common",
        "advantage vs vermin disease 24h; cleans and slows infection in fresh wounds. treats leaf-bare cough and liver complaints; drives off fleas. excessive intake causes vomiting.",
        cures=("leafbare_cough", "fleas", "infected_wound", "hepatitis", "leptospirosis"),
        side_effects="generally safe; excessive intake may cause nausea, vomiting, diarrhea.",
        preparation="eaten raw or cooked; tea.",
    ),
    "willow_bark": _h(
        "Willow Bark",
        "common",
        "pain relief 1 sunrise; cools fever. ignores chronic pain and arthritis penalties for 1 sunrise. contains salicin; natural anti-inflammatory for joints and fractures. stomach bleeding possible with long-term use.",
        packs=("mistmoor", "silverrush"),
        cures=("influenza", "sprained_leg", "fractured_rib", "lyme", "arthritis"),
        side_effects="common: nausea, vomiting, diarrhea, heartburn, rash; may affect blood clotting; similar to aspirin.",
        preparation="bark chewed in small amounts for pain; tea, tincture.",
    ),
    "wintergreen": _h(
        "Wintergreen",
        "restricted",
        "often misidentified; 1d4 poison (dc 10). oil is unsafe to eat. external redness and irritation; large amounts cause tinnitus, confusion, and death.",
        poison=True,
        side_effects="oil is unsafe to take orally; topical: redness, irritation; large amounts cause ringing in ears, nausea, confusion.",
        preparation="external use only; tea with caution; oil externally; diluted.",
    ),
    "witch_hazel": _h(
        "Witch Hazel",
        "common",
        "astringent and hemostatic; reduces eye swelling; soothes poison ivy rash and insect stings; eases chest cough. internal use in large doses may cause liver problems.",
        cures=("swollen_eye", "infected_wound", "poison_ivy", "leafbare_cough", "mild_poison"),
        side_effects="most common: dry skin; high doses may cause liver or kidney problems; contains trace safrole.",
        preparation="topical application; distillate or cream; internal use with caution.",
    ),
    "wolfsbane": _h(
        "Wolfsbane",
        "very_rare",
        "removes spirit curse (dc 20 medicine check); deals 2d6 poison damage to patient. extremely toxic; all parts poisonous; historically used to poison wolves. can be absorbed through skin.",
        packs=("greyspire",),
        cures=("spirit_curse",),
        poison=True,
        side_effects="extremely toxic; all parts poisonous; contains aconitine; ingestion causes numbness, nausea, respiratory failure; can be absorbed through skin.",
        preparation="no safe preparation for lay herbalists.",
    ),
    "yarrow": _h(
        "Yarrow",
        "common",
        "+2 medicine to stabilize; stops bleeding; cleanses torn claws. anti-inflammatory; lowers blood pressure. also settles gut sickness. allergic reactions possible.",
        cures=("deep_gash", "infected_wound", "shaking_sickness", "torn_claw", "diarrhea"),
        side_effects="generally considered safe; may interact with lithium; allergic reactions possible.",
        preparation="tea, tincture, topical application.",
    ),
    "catmint": _h(
        "Catmint Tea",
        "uncommon",
        "cures severe blackcough (2 doses per 24 hours); eases anxiety, insomnia, and eating troubles. large doses cause vomiting. not for pregnant wolves.",
        habitat=("compound",),
        cures=("cough", "leafbare_cough", "anxiety", "insomnia", "eating_distress", "asthma"),
        side_effects="high doses possibly unsafe; headaches, vomiting; emmenagogue and abortifacient; avoid in pregnancy.",
        preparation="leaves and flowers for congestion and coughs; tea.",
    ),
    "purslane": _h(
        "Purslane",
        "common",
        "fleshy leaves hold ditch-water; chew for +12 thirst without visiting the creek. anti-inflammatory; eases eating distress and anxiety.",
        habitat=("roadside", "compound"),
        cures=("eating_distress", "anxiety"),
        side_effects="limited studies; no significant adverse effects; constipation reported; contains oxalates.",
        preparation="eaten as vegetable; cooking reduces oxalates.",
    ),
    "chicory": _h(
        "Chicory",
        "common",
        "settles gut upset, diarrhea, and eating distress; supports liver health and hepatitis recovery. high fiber may cause gas and bloating.",
        habitat=("roadside",),
        cures=("diarrhea", "eating_distress", "hepatitis"),
        side_effects="fresh plant may cause allergic skin reactions; high fiber may cause gas, bloating, diarrhea.",
        preparation="root as coffee substitute; tea.",
    ),
    "mugwort": _h(
        "Mugwort",
        "uncommon",
        "rub through pelt to drive off fleas; settles gut upsets and eating distress. toxic in pregnancy; causes miscarriage.",
        habitat=("roadside",),
        cures=("fleas", "diarrhea", "eating_distress"),
        side_effects="contains thujone; harmful in large amounts; may cause miscarriage; respiratory allergic responses.",
        preparation="tea, topical; use with caution.",
    ),
    "garden_mint": _h(
        "Garden Mint",
        "common",
        "ends nausea in minutes; eases stomach cramps, eating troubles, diarrhea, and bloat. antimicrobial.",
        habitat=("compound",),
        cures=("eating_distress", "diarrhea", "bloat", "infected_wound"),
        side_effects="may cause sleepiness; concentrated oils toxic to dogs and cats in large quantities.",
        preparation="tea, culinary herb.",
    ),
    "wood_sorrel": _h(
        "Wood Sorrel",
        "common",
        "steadies a queasy stomach; treats eating distress and influenza fever. contains oxalic acid; high doses are toxic; causes kidney damage.",
        habitat=("compound",),
        cures=("influenza", "eating_distress"),
        side_effects="contains oxalic acid; high doses toxic; overdose causes diarrhea, nausea, kidney damage.",
        preparation="small amounts as tonic; poultice.",
    ),
    "oxeye_daisy": _h(
        "Oxeye Daisy",
        "common",
        "eases joint ache and sprains; suppresses leaf-bare cough; aids liver complaints and influenza. antispasmodic; diuretic; clears urinary complaints. allergic reactions in asteraceae-sensitive wolves.",
        habitat=("roadside",),
        cures=("sprained_leg", "leafbare_cough", "influenza", "hepatitis", "urinary_infection"),
        side_effects="may cause allergic reactions in those sensitive to asteraceae; may cause contact and inhalant allergy.",
        preparation="young leaves in salads; tea.",
    ),
    "common_mallow": _h(
        "Common Mallow",
        "common",
        "poultice for scraped and scorched pads; soothes dry cough and eating distress.",
        habitat=("roadside", "compound"),
        cures=("punctured_paw", "leafbare_cough", "eating_distress", "scorched_hide", "asthma"),
        side_effects="none known; may lower blood sugar; livestock poisoning reported; muscular tremors.",
        preparation="tea, topical, bath.",
    ),
    "shepherds_purse": _h(
        "Shepherd's Purse",
        "common",
        "hemostatic; stops internal and external bleeding; treats deep gash and internal bleeding. toxic in pregnancy; causes uterine contractions.",
        habitat=("roadside",),
        cures=("deep_gash", "internal_bleeding"),
        side_effects="possibly safe in small amounts short-term; large amounts cause heart palpitations; causes uterine contractions; avoid pregnancy.",
        preparation="tea, tincture, powder.",
    ),
    "garlic_mustard": _h(
        "Garlic Mustard",
        "common",
        "rub through pelt to drive off fleas; antiseptic poultice for infected bites and wounds; neutralizes mild poison; eases leaf-bare cough and lyme.",
        habitat=("roadside",),
        cures=("leafbare_cough", "infected_wound", "mild_poison", "lyme"),
        side_effects="safe in moderate amounts; large quantities may cause digestive discomfort; contains goitrogens.",
        preparation="young leaves eaten; poultice.",
    ),
}