# Full Basil herb compendium; inventory keys via herbs.herb_inventory_key (stick → "stick")
# habitat: where a herb can be gathered - "wild" (territory), "roadside", "compound"

def _h(name, rarity, effect, packs=(), cures=(), poison=False, habitat=("wild",)):
    return {
        "name": name,
        "rarity": rarity,
        "packs": packs,
        "effect": effect,
        "cures": cures,
        "poison": poison,
        "habitat": habitat,
    }


HERBS = {
    "adders_tongue": _h(
        "Adder's Tongue",
        "common",
        "Reroll failed poison save with advantage if within 1 minute.",
        cures=("mild_poison", "poison_ivy"),
    ),
    "alder_bark": _h(
        "Alder Bark",
        "uncommon",
        "Cures toothache and gum inflammation.",
        ("silverrush",),
        cures=("broken_tooth",),
    ),
    "arnica": _h(
        "Arnica",
        "rare",
        "Halves bruise/sprain recovery (external only).",
        ("greyspire",),
        cures=("sprained_leg", "punctured_paw"),
    ),
    "beech_leaves": _h(
        "Beech Leaves",
        "common",
        "Carry herbs; nut oil prevents infection 24h.",
        cures=("infected_wound",),
    ),
    "bindweed": _h(
        "Bindweed Vines",
        "common",
        "Vines lash straight sticks around a broken leg to set the break; with comfrey −1 week healing.",
        cures=("fractured_rib", "sprained_leg", "spinal_injury"),
    ),
    "blackberry": _h(
        "Blackberry (Bramble)",
        "common",
        "Soothes insect stings; ends non-magical venom poison.",
        cures=("mild_poison", "fleas"),
    ),
    "bloodroot": _h("Bloodroot", "restricted", "3d6 poison damage (DC 16 half).", poison=True),
    "boneset": _h(
        "Boneset",
        "common",
        "Reroll failed disease save with advantage; take better. Slows early rabies (one sunrise, no cure).",
        ("mistmoor",),
        cures=("influenza", "redscratch"),
    ),
    "borage": _h(
        "Borage",
        "common",
        "Extra milk for nursing mother; one additional pup.",
        cures=("diarrhea", "wasting_sickness", "anxiety", "grief_melancholy"),
    ),
    "broom": _h(
        "Broom",
        "common",
        "Bind broken bones; move at half speed without worsening.",
        cures=("fractured_rib", "sprained_leg", "broken_jaw"),
    ),
    "burdock_root": _h(
        "Burdock Root",
        "common",
        "Poultice removes infection after 24h rest.",
        cures=("mange", "hepatitis"),
    ),
    "burnet": _h(
        "Burnet",
        "common",
        "1 leaf/day ignores first exhaustion from forced march.",
        cures=("sprained_leg",),
    ),
    "catchweed": _h(
        "Catchweed Burrs",
        "common",
        "Holds poultices; extends duration 4 hours.",
        cures=("deep_gash",),
    ),
    "cattail": _h(
        "Cattail",
        "common",
        "Stops bleeding like yarrow.",
        ("silverrush",),
        cures=("deep_gash",),
    ),
    "celandine": _h(
        "Celandine",
        "common",
        "Removes minor eye blindness within 1 hour.",
        cures=("partial_blindness", "torn_ear"),
    ),
    "chamomile": _h(
        "Chamomile",
        "common",
        "Advantage on Wisdom saves vs fear for 1 hour.",
        habitat=("compound",),
        cures=("concussion", "dementia", "anxiety", "insomnia", "grief_melancholy", "shock_emotional"),
    ),
    "chervil": _h(
        "Chervil",
        "common",
        "Removes nausea; eases redscratch itch.",
        cures=("redscratch", "diarrhea"),
    ),
    "chickweed": _h(
        "Chickweed",
        "common",
        "Ends whitecough (3 doses/24h).",
        habitat=("roadside", "compound"),
        cures=("mild",),
    ),
    "cobnuts": _h("Cobnuts", "common", "+1 Stealth when approaching prey.", cures=("fleas",)),
    "cobwebs": _h(
        "Cobwebs",
        "common",
        "Auto-stabilize dying wolf; bandages deep gashes.",
        cures=("dying", "deep_gash", "shaking_sickness"),
    ),
    "coltsfoot": _h("Coltsfoot", "common", "Ends whitecough after 1 dose.", cures=("mild",)),
    "comfrey": _h(
        "Comfrey",
        "uncommon",
        "Poultice heals 1d4 HP on deep wounds.",
        ("thistlehide",),
        cures=("sprained_leg", "fractured_rib", "broken_jaw", "deep_gash", "spinal_injury"),
    ),
    "coneflower": _h(
        "Coneflower (Echinacea)",
        "common",
        "Advantage on infection saves within 1h of injury.",
        ("greyspire",),
        cures=("infected_wound", "pox"),
    ),
    "daisy": _h(
        "Daisy",
        "common",
        "Ignore arthritis pain penalties 8 hours.",
        cures=("sprained_leg", "fractured_rib"),
    ),
    "dandelion": _h(
        "Dandelion",
        "common",
        "Soothes stings; reduces headache pain.",
        habitat=("roadside", "compound"),
        cures=("mild_poison", "fleas"),
    ),
    "deadly_nightshade": _h(
        "Deadly Nightshade",
        "restricted",
        "Confusion then paralysis (Wis DC 15).",
        poison=True,
    ),
    "deathberries": _h(
        "Deathberries (Yew)",
        "restricted",
        "Mercy killing; Medic knowledge only.",
        poison=True,
    ),
    "dried_skullcap": _h(
        "Dried Skullcap",
        "uncommon",
        "Sedative rest for concussion recovery.",
        cures=("concussion", "dementia", "feral_shift", "anxiety", "delirium", "obsession", "pack_madness"),
    ),
    "dock": _h(
        "Dock",
        "common",
        "Restores cracked paw pads after 1 day rest.",
        cures=("punctured_paw",),
    ),
    "douglas_sagewort": _h(
        "Douglas' Sagewort",
        "common",
        "Prevents infection 24h; advantage vs fear 1h.",
        cures=("infected_wound", "distemper", "chronic_stress", "anxiety", "pack_madness"),
    ),
    "edelweiss": _h(
        "Edelweiss",
        "very_rare",
        "Ends bellyache; suppresses cough 4h.",
        ("greyspire",),
        cures=("diarrhea", "mild"),
    ),
    "elder": _h(
        "Elder (external)",
        "common",
        "Treats sprains; toxic if eaten (DC 14 or 2d4 poison).",
        cures=("sprained_leg",),
    ),
    "elderberry": _h(
        "Elderberry",
        "rare",
        "Advantage on disease saves for 3 sunrises.",
        ("mistmoor",),
        cures=("distemper", "influenza"),
    ),
    "fennel": _h(
        "Fennel",
        "common",
        "Extra day without food before exhaustion.",
        habitat=("compound",),
        cures=("diarrhea",),
    ),
    "feverfew": _h(
        "Feverfew",
        "common",
        "Advantage on disease saves for 1 day.",
        cures=("influenza", "redscratch", "pox", "rot_lung", "milk_fever"),
    ),
    "foxglove": _h(
        "Foxglove",
        "restricted",
        "Deadly heart poison (DC 18 or die in 1d4 min).",
        poison=True,
    ),
    "goldenrod": _h(
        "Goldenrod",
        "rare",
        "+2 HP per 8h rest. Slows early rabies (+2 next save, no cure).",
        cures=("infected_wound", "deep_gash"),
    ),
    "heather": _h(
        "Heather",
        "common",
        "Sweetens bitter herb mixtures.",
        cures=("mild_poison",),
    ),
    "holly_berries": _h("Holly Berries", "restricted", "2d4 poison (DC 12 half).", poison=True),
    "honey": _h("Honey", "common", "Feeds starving pups (+10 hunger, −1 exhaustion); sweetens `/pupcare action:feed`. Adults: −1 starvation exhaustion when depleted.", cures=("diarrhea", "mild")),
    "horsetail": _h(
        "Horsetail",
        "common",
        "+3 Medicine to stabilize dying.",
        cures=("torn_claw", "punctured_paw"),
    ),
    "ivy_vines": _h(
        "Ivy Vines",
        "common",
        "Preserves dried herbs 2 extra weeks.",
        cures=("mange",),
    ),
    "jewelweed": _h(
        "Jewelweed",
        "common",
        "Touch-me-not sap neutralizes poison-ivy rash; cools bee and nettle stings.",
        habitat=("roadside", "wild"),
        cures=("poison_ivy", "mild_poison"),
    ),
    "juniper_berry": _h(
        "Juniper Berries",
        "common",
        "Cures mild poison or nausea.",
        cures=("mild_poison", "diarrhea"),
    ),
    "knotgrass": _h(
        "Knotgrass",
        "common",
        "Cures diarrhea; kills worms/fleas in 1 day.",
        habitat=("roadside", "compound"),
        cures=("diarrhea", "fleas"),
    ),
    "labrador_tea": _h(
        "Labrador Tea",
        "common",
        "Ends wheezing for 4 hours.",
        cures=("mild", "severe"),
    ),
    "lambs_ear": _h(
        "Lamb's Ear",
        "common",
        "Advantage on disease saves until next sunrise.",
        habitat=("roadside",),
        cures=("fleas", "mange"),
    ),
    "lavender": _h(
        "Lavender",
        "common",
        "Cures fever/chills; hides death-scent at burial.",
        habitat=("compound",),
        cures=("influenza", "redscratch", "insomnia", "anxiety", "grief_melancholy", "night_terrors"),
    ),
    "mullein": _h(
        "Mullein",
        "rare",
        "Heals yellowcough and rot-lung lung damage; Medics use it for full recovery.",
        ("greyspire", "mistmoor"),
        habitat=("roadside",),
        cures=("yellowcough", "rot_lung", "cancer"),
    ),
    "lungwort": _h(
        "Lungwort",
        "rare",
        "Also heals yellowcough and rot-lung when mullein is scarce.",
        ("greyspire", "mistmoor"),
        cures=("yellowcough", "rot_lung", "cancer"),
    ),
    "marsh_mallow": _h(
        "Marsh-Mallow Root",
        "uncommon",
        "Soothes rot-lung fever and wheeze; prized by Mistmoor healers.",
        ("mistmoor",),
        cures=("rot_lung",),
    ),
    "belly_rip_fungus": _h(
        "Belly-Rip Fungus",
        "rare",
        "Glow-fungus from the Belly-Rip sinkhole; only cure for rot-lung necrosis.",
        ("mistmoor",),
        cures=("rot_lung",),
    ),
    "lizards_tail": _h(
        "Lizard's Tail",
        "common",
        "Removes 1 fever exhaustion.",
        ("mistmoor",),
        cures=("influenza",),
    ),
    "meadowsweet": _h(
        "Meadowsweet",
        "uncommon",
        "Ignore 1 pain exhaustion 4h.",
        ("silverrush",),
        cures=("sprained_leg", "fractured_rib", "chronic_stress", "eating_distress", "obsession"),
    ),
    "mountain_ash": _h(
        "Mountain Ash (Rowan)",
        "common",
        "Bitter bark eases fever and hard-pad distemper.",
        cures=("distemper",),
    ),
    "oak_bark": _h(
        "Oak Bark",
        "common",
        "Stops bleeding; +2 stabilize.",
        ("thistlehide",),
        cures=("deep_gash", "infected_wound"),
    ),
    "oleander": _h("Oleander", "restricted", "4d6 poison, no antidote (DC 18 half).", poison=True),
    "parsley": _h(
        "Parsley",
        "common",
        "Ends lactation within 6 hours; eases milk-fever.",
        habitat=("compound",),
        cures=("diarrhea", "milk_fever", "wasting_sickness"),
    ),
    "passionflower": _h(
        "Passionflower",
        "uncommon",
        "Eases racing thoughts and nightmare sleep.",
        habitat=("compound",),
        cures=("anxiety", "insomnia", "night_terrors"),
    ),
    "pine_needle": _h("Pine Needles", "common", "Tea ends coughing after 1 dose.", cures=("severe",)),
    "pine_bark": _h(
        "Pine Bark",
        "common",
        "Inner bark strips ease Leaf-bare cough and frost-nipped paws; Greyspire medics peel it in cold weather.",
        ("greyspire",),
        cures=("severe", "punctured_paw"),
    ),
    "plantain": _h(
        "Plantain",
        "uncommon",
        "Gentle wound remedy.",
        ("thistlehide",),
        habitat=("roadside", "compound"),
        cures=("deep_gash", "punctured_paw"),
    ),
    "poison_ivy": _h(
        "Poison Ivy",
        "restricted",
        "Contact: −1d4 CHA, disadvantage Stealth 3 days.",
        poison=True,
    ),
    "poppy_seeds": _h(
        "Poppy Seeds",
        "common",
        "Sedative and pain relief; unconscious rest 1 sunrise.",
        cures=("concussion", "insomnia", "anxiety", "shock_emotional", "night_terrors"),
    ),
    "prickly_ash": _h(
        "Prickly Ash",
        "rare",
        "Ends frozen-paw numbness; numbs tooth pain 1h.",
        ("greyspire",),
        cures=("punctured_paw", "broken_tooth"),
    ),
    "purple_loosestrife": _h(
        "Purple Loosestrife",
        "common",
        "Staunches bleeding on stitched wounds; reduces bleed timer; cures diarrhea.",
        ("silverrush",),
        habitat=("roadside",),
        cures=("deep_gash", "diarrhea"),
    ),
    "ragweed": _h(
        "Ragweed",
        "common",
        "3 leaves removes 1 exhaustion.",
        habitat=("roadside",),
        cures=("fleas",),
    ),
    "ragwort": _h(
        "Ragwort",
        "common",
        "Elder hunts at full speed for 1 day.",
        cures=("sprained_leg",),
    ),
    "raspberry_leaves": _h(
        "Raspberry Leaves",
        "common",
        "Advantage on birth hemorrhage saves.",
        cures=("deep_gash",),
    ),
    "rosemary": _h(
        "Rosemary",
        "common",
        "Hides death-scent at burial.",
        habitat=("compound",),
        cures=("mange", "dementia", "grief_melancholy", "obsession"),
    ),
    "rush_stalks": _h(
        "Rush Stalks",
        "common",
        "Hard stalks bind broken bones; lash splints with sticks (+2 Medicine to set fractures).",
        ("mistmoor", "silverrush"),
        cures=("fractured_rib", "broken_jaw", "sprained_leg"),
    ),
    "saffron": _h(
        "Saffron",
        "common",
        "Auto-stabilize postpartum hemorrhage; ends milk-fever.",
        cures=("dying", "milk_fever"),
    ),
    "sage": _h(
        "Sage",
        "common",
        "Soothes sore throat; elders eat hard food longer.",
        cures=("mild", "redscratch"),
    ),
    "skunk_cabbage": _h(
        "Skunk Cabbage (dried)",
        "common",
        "Treats severe cough; toxic if fresh (DC 12).",
        cures=("severe",),
    ),
    "slippery_elm": _h(
        "Slippery Elm",
        "uncommon",
        "Eat/drink without pain 8 hours.",
        ("thistlehide",),
        cures=("broken_jaw",),
    ),
    "snakeroot": _h("Snakeroot", "common", "Advantage vs snake venom saves.", cures=("mild_poison",)),
    "sorrel": _h("Sorrel", "common", "Stops heavy bleeding; restores appetite.", cures=("deep_gash",)),
    "stick": _h(
        "Straight Stick",
        "common",
        "Thin twig for wolves in pain to bite during deep treatment; also used to lash splints.",
        habitat=("wild",),
        cures=(),
    ),
    "sticklewort": _h(
        "Sticklewort",
        "common",
        "Neutralizes snake venom if within 1 minute.",
        cures=("mild_poison",),
    ),
    "stinging_nettle": _h(
        "Stinging Nettle",
        "common",
        "With comfrey +1 broken bone healing.",
        cures=("fractured_rib", "sprained_leg"),
    ),
    "swamp_milkweed": _h(
        "Swamp Milkweed",
        "very_rare",
        "Breaks curses; cures deadly disease.",
        ("mistmoor",),
        cures=("deadly", "pox"),
    ),
    "sweet_sedge": _h(
        "Sweet Sedge",
        "common",
        "Ends mild gut infection in 1 day; steadies Belly-Rip tremors.",
        cures=("diarrhea", "shaking_sickness"),
    ),
    "tansy": _h("Tansy", "common", "Halves sprain recovery time.", cures=("sprained_leg",)),
    "thyme": _h(
        "Thyme",
        "common",
        "Ends minor pain 2 hours.",
        habitat=("compound",),
        cures=("mild", "fleas"),
    ),
    "tormentil": _h(
        "Tormentil",
        "common",
        "+2 Medicine for any injury.",
        cures=("infected_wound", "deep_gash"),
    ),
    "valerian": _h(
        "Valerian",
        "common",
        "Calms shock; unconscious 1d4 hours.",
        cures=("concussion", "insomnia", "anxiety", "night_terrors", "shock_emotional"),
    ),
    "watermint": _h("Watermint", "common", "Removes nausea in 10 minutes.", cures=("diarrhea",)),
    "water_hemlock": _h(
        "Water Hemlock",
        "restricted",
        "Lethal poison (DC 20 half, still 6d6).",
        poison=True,
    ),
    "wild_cherry_bark": _h(
        "Wild Cherry Bark",
        "common",
        "Stops coughing 2 hours, even blackcough.",
        cures=("severe", "mild"),
    ),
    "wild_garlic": _h(
        "Wild Garlic",
        "common",
        "Advantage vs vermin disease 24h.",
        cures=("hepatitis", "fleas"),
    ),
    "willow_bark": _h(
        "Willow Bark",
        "common",
        "Pain relief 1 sunrise; cools marsh fever.",
        ("mistmoor",),
        cures=("sprained_leg", "fractured_rib", "rot_lung"),
    ),
    "wintergreen": _h(
        "Wintergreen",
        "restricted",
        "Often misidentified; 1d4 poison (DC 10).",
        poison=True,
    ),
    "witch_hazel": _h(
        "Witch Hazel",
        "common",
        "Astringent: reduces swelling; soothes insect stings and bruises; eases eye strain.",
        cures=("torn_ear", "partial_blindness", "mild_poison", "fleas", "sprained_leg", "punctured_paw"),
    ),
    "wolfsbane": _h(
        "Wolfsbane",
        "very_rare",
        "Removes spirit curse (DC 20 Med); 2d6 poison to patient.",
        cures=("pox",),
    ),
    "yarrow": _h(
        "Yarrow",
        "common",
        "+2 Medicine to stabilize; stops bleeding.",
        cures=("deep_gash", "infected_wound", "shaking_sickness"),
    ),
    "catmint": _h(
        "Catmint Tea",
        "uncommon",
        "Cures severe blackcough (2 doses/24h); eases anxiety.",
        habitat=("compound",),
        cures=("severe", "anxiety"),
    ),
    "purslane": _h(
        "Purslane",
        "common",
        "Fleshy leaves hold ditch-water; chew for +12 thirst without visiting the creek.",
        habitat=("roadside", "compound"),
        cures=("diarrhea",),
    ),
    "chicory": _h(
        "Chicory",
        "common",
        "Bitter roadside root; settles a gut upset by garbage or nerves.",
        habitat=("roadside",),
        cures=("diarrhea",),
    ),
    "mugwort": _h(
        "Mugwort",
        "uncommon",
        "Gravel-ditch mugwort; rub through pelt to drive off fleas.",
        habitat=("roadside",),
        cures=("fleas", "mange"),
    ),
    "garden_mint": _h(
        "Garden Mint",
        "common",
        "Escaped from a Twoleg herb bed; ends nausea in minutes.",
        habitat=("compound",),
        cures=("diarrhea", "mild_poison"),
    ),
    "wood_sorrel": _h(
        "Wood Sorrel",
        "common",
        "Sour shamrock in mowed lawn; steadies a queasy stomach after edging too close.",
        habitat=("compound",),
        cures=("diarrhea",),
    ),
    "oxeye_daisy": _h(
        "Oxeye Daisy",
        "common",
        "Thunderpath-margin daisy; eases joint ache like its meadow kin.",
        habitat=("roadside",),
        cures=("sprained_leg",),
    ),
    "common_mallow": _h(
        "Common Mallow",
        "common",
        "Soft leaves in roadside dust; mild poultice for scraped pads.",
        habitat=("roadside", "compound"),
        cures=("punctured_paw",),
    ),
    "shepherds_purse": _h(
        "Shepherd's Purse",
        "common",
        "Triangular seed-pods along the gravel; slows oozing cuts.",
        habitat=("roadside",),
        cures=("deep_gash",),
    ),
    "garlic_mustard": _h(
        "Garlic Mustard",
        "common",
        "Invasive roadside mustard; rub through pelt to drive off fleas.",
        habitat=("roadside",),
        cures=("fleas",),
    ),
}
