"""Canonical wolf bonds from character lore; applied when both wolves are registered."""

from __future__ import annotations

# Each entry: wolf_a, wolf_b (names match CHARACTER_LORE_BY_NAME), bond_type, strength, note.
# Bonds are symmetric; wolf_a/b order does not matter.

CANONICAL_BONDS: list[dict] = [
    # --- Mistmoor ---
    {
        "a": "Mirewort",
        "b": "Puddlebane",
        "type": "rivalry",
        "strength": 64,
        "note": "He cannot forgive how easily she treats the dead as garden; she cannot forgive how he wears grief like law.",
    },
    {
        "a": "Mirewort",
        "b": "Murkvein",
        "type": "rivalry",
        "strength": 55,
        "note": "Rotmother envies the Maw's attention to him; he keeps Belly-Rip secrets she cannot stomach.",
    },
    {
        "a": "Mirewort",
        "b": "Dusk",
        "type": "rivalry",
        "strength": 42,
        "note": "Whisper-Jaw spies on Belly-Rip visits; pups trust Mirewort, and Dusk hates filing what he will not act on.",
    },
    {
        "a": "Mirewort",
        "b": "Mudnose",
        "type": "friendship",
        "strength": 52,
        "note": "Quiet respect over Sedgepup's grave and shared silence in the mud.",
    },
    {
        "a": "Mirewort",
        "b": "Mosspup",
        "type": "mentor",
        "strength": 70,
        "note": "Apprentice healer; training in rot-lung and marsh remedies.",
    },
    {
        "a": "Mirewort",
        "b": "Soot",
        "type": "mentor",
        "strength": 68,
        "note": "Trainee medic; hopeless earnestness he refuses to send away.",
    },
    {
        "a": "Mirewort",
        "b": "Rotteddust",
        "type": "mentor",
        "strength": 65,
        "note": "Apprentice poison-craft and stitching; patience stretched thin.",
    },
    {
        "a": "Murkvein",
        "b": "Dusk",
        "type": "friendship",
        "strength": 78,
        "note": "Second and Whisper-Jaw; loyalty beneath the rasp.",
    },
    {
        "a": "Reedwhisper",
        "b": "Murkvein",
        "type": "friendship",
        "strength": 50,
        "note": "Diplomat to the Rotmother; patience against the swamp's teeth.",
    },
    # --- Greyspire ---
    {
        "a": "Ironjaw",
        "b": "Slate",
        "type": "rivalry",
        "strength": 58,
        "note": "Secretly competitive hunters; respect without warmth.",
    },
    {
        "a": "Grim",
        "b": "Icefang",
        "type": "friendship",
        "strength": 62,
        "note": "Alpha and senior hunter; mountain law in practice.",
    },
    # --- Silverrush ---
    {
        "a": "Saltmuzzle",
        "b": "Rift",
        "type": "friendship",
        "strength": 75,
        "note": "Beta devoted to her protection; guilt over the raid that killed her mate.",
    },
    {
        "a": "Ripple",
        "b": "Cinder",
        "type": "friendship",
        "strength": 65,
        "note": "Found him after the wildfire; permitted him to stay.",
    },
    {
        "a": "Saltmuzzle",
        "b": "Cinder",
        "type": "mentor",
        "strength": 60,
        "note": "Mentored after the fire; river pack took him in.",
    },
    {
        "a": "Saltmuzzle",
        "b": "Driftpup",
        "type": "mentor",
        "strength": 58,
        "note": "Rogue-born pup taken into Silverrush under her eye.",
    },
    {
        "a": "Saltmuzzle",
        "b": "Riptide",
        "type": "mentor",
        "strength": 58,
        "note": "Rogue-born hunter she steadied into the pack.",
    },
    {
        "a": "Vulcan Stonehide",
        "b": "Aromis",
        "type": "mentor",
        "strength": 56,
        "note": "Both scarred outsiders Silverrush took in; Vulcan looks out for him the way he couldn't for Zephyr.",
    },
    {
        "a": "Ripplepup",
        "b": "Pebble",
        "type": "kin",
        "strength": 70,
        "note": "Father diplomat of the litter.",
    },
    # --- Thistlehide ---
    {
        "a": "Finnpelt",
        "b": "Mossgaze",
        "type": "kin",
        "strength": 72,
        "note": "Younger sibling; public coldness, secret hyper-protection.",
    },
    {
        "a": "Brackenpelt",
        "b": "Cloverfern",
        "type": "kin",
        "strength": 85,
        "mates": True,
        "note": "Mates; southern border hunter and forager.",
    },
    {
        "a": "Brackenpelt",
        "b": "Sypha",
        "type": "kin",
        "strength": 78,
        "note": "Father and Fur-Giver daughter.",
    },
    {
        "a": "Cloverfern",
        "b": "Sypha",
        "type": "kin",
        "strength": 78,
        "note": "Mother and Fur-Giver daughter.",
    },
    {
        "a": "Sypha",
        "b": "Firepaw",
        "type": "mentor",
        "strength": 74,
        "note": "Blind medic apprentice; taught by touch and scent.",
    },
    {
        "a": "Mossheart",
        "b": "Rivenmaw",
        "type": "romance",
        "strength": 72,
        "note": "Secret lovers at the neutral bend; forbidden warmth.",
    },
    {
        "a": "Ashbark",
        "b": "Fernspot",
        "type": "kin",
        "strength": 58,
        "mates": True,
        "note": "Mates in the same den; cold and strained; Kanami between them.",
    },
    {
        "a": "Ashbark",
        "b": "Kanami",
        "type": "kin",
        "strength": 45,
        "note": "Abandoned daughter; guilt and silence.",
    },
    {
        "a": "Fernspot",
        "b": "Kanami",
        "type": "kin",
        "strength": 40,
        "note": "Abandoned daughter; they do not speak of her.",
    },
    {
        "a": "Kanami",
        "b": "RiverShroud",
        "type": "mentor",
        "strength": 65,
        "note": "Foster guardian after abandonment.",
    },
    {
        "a": "RiverShroud",
        "b": "Pale'Step",
        "type": "mentor",
        "strength": 62,
        "note": "Foster ward; antlered Alpha's charge.",
    },
    {
        "a": "Skye",
        "b": "Finnpelt",
        "type": "friendship",
        "strength": 55,
        "note": "Greyspire veteran; one of few who has seen him vulnerable.",
    },
    {
        "a": "Eltanin",
        "b": "Lucid",
        "type": "friendship",
        "strength": 48,
        "note": "Quiet border hunters; mutual respect in silence.",
    },
]
